### PR TITLE
Added support to save an image from url

### PR DESCRIPTION
**Pull request by anasAsh**
- a file path could contain dots, using explode instead of prey_match and it’s faster to use explode.
  - added support to save an image from url.
  - added another check for the image extension using exif_imagetype

i have been working on this on my personal project, and thought it should be patched, tell me in case u need me to do any changes.

### CODE REVIEW

**Comment by gregmolnar** [comment]
@craigpotter could you please review this?

**Comment by craigpotter** [comment]
I will take a good look and do some testing one evening this week. 

From a first glace, @anasAsh Could you rename $full_bath to $full_path. 

Can you also give an example of how you are saving from an image or from a URL.

**Comment by anasAsh** [comment]
Hi @craigpotter
here is an example, it should be very straight forward.

``` php
$model->image = "https://avatars1.githubusercontent.com/u/1442635?v=2&s=96":
$model->save();
```

**Comment by craigpotter** [comment]
Hi Sorry for the delay. 

For getting the ext you seem to be using Explode however you have left preg_match in the code in certain places. 

Its not used and not needed. We need to decide if explode or preg_match is the best way. After thinking about it, I think explode is a little easier to read and may be faster than preg_match 

Also Array_pop vs End is an intersting conflict. array_pop will remove it from the array which could cause issues in further enhancements. I think end() might be a better solution unless you can come up with reason other wise ?

**Comment by craigpotter** [comment]
This enhancement isn't compatible with PHP < 5.4. It uses short syntax 
Also it seems you have stopped attachments that are not images being uploaded. What if the user tries to attach a .doc or .pdf

```
throw new CException('This is not an image that we can process.');
```

This is a bad way and removes support
Please fix and resubmit.

**Pull request closed without merging**
