### PR TITLE
Path template can now include of owner derived attribute values.

### PR DESCRIPTION
**Pull request by bravoman**
Added the ability to make the path template use attributes of the owner object while saving the attachment like so `':folder/:{someAttributeOfTheOwner}/:id/:filename.:ext'`. You can even use attibutes of relations like so `:{user.username}`. Should also work with multiple relations through other relations like so `:{user.userSettings.imageSavePath}`. User has to a relation of the owner object. All the relations obviously need to be has_one or belongs_to for this to work.

### CODE REVIEW

**Comment by bravoman** [comment]
I also made changes to the readme.md which I will send a pull request for after you commited these changes.

**Comment by bravoman** [comment]
Oh, I see it has allready been added ;)

**Comment by gregmolnar** [comment]
Cheers

**Comment by bravoman** [comment]
Cheers :)

**Pull request merged**
